fireBase:
  collection: tripLiveTracking
  dbBaseUrl: https://XXXXXX.firebaseio.com
  authFileLocation: xxxxxxxxxxx.adminsdk.json
  ideaTimeSpanInMinute: 5
  liveTrackingIntervalInSecond: 2

googleMap:
  baseUrl: https://maps.googleapis.com/maps/api/distancematrix/json
  apiKey: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  mode: bus